version: "3.8"

services:
  mysql:
    container_name: mysql
    platform: linux/amd64
    image: mysql:8-oracle
    volumes:
      - ./local-db/conf:/etc/mysql/conf.d
      - ./local-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "23306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 102030
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - local-net

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "26379:6379"  # 호스트의 26379 포트와 컨테이너의 6379 포트(기본 Redis 포트)를 매핑
    networks:
      - local-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - action.auto_create_index=true # 자동 인덱스 생성 활성화
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data1:/usr/share/elasticsearch/data
    networks:
      - local-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - local-net

volumes:
  es_data1:
    driver: local

networks:
  local-net:
    driver: bridge
    external: true
    name: docker_local-net
