spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  application:
    name: feed

  elasticsearch:
    rest:
      uris: http://localhost:9200

  #  db
  datasource:
    url: jdbc:mysql://localhost:23306/local_db
    username: root
    password: 102030

  #  redis
  data:
    redis:
      host: localhost
      port: 26379
    elasticsearch:
      repositories:
        enabled: true
      repository:
        refresh-interval: 1s

  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug

